sonar.projectKey=aochoae_aeterna
sonar.organization=luisalberto
sonar.projectVersion=1.0.0.dev1
sonar.sources=packages
sonar.tests=tests
sonar.exclusions=venv/**,.pytest_cache/**,docs/_build/**,**/tests/**,tools/**
sonar.python.coverage.reportPaths=coverage.xml
